name: Using Variables
on:
  push:
  workflow_dispatch:

env:
  WORKFLOW_VAR: 'I am a workflow env var'
  OVERWRITTEN: 'I will be overwritten'
jobs:
  echo:
    runs-on: ubuntu-latest
    env:
      JOB_VAR: 'I am a job env var'
      OVERWRITTEN: 'i have been overwritten at the job level'
    steps:
      - name: Print Env Variables
        env:
          STEP_VAR: "I am a step env var"
          step_var2: "i am another step env var"
        run: |
          echo "Step env var: ${{env.STEP_VAR}}"
          echo "Step env var 2: $step_var"
          echo "Job env var: ${{env.JOB_VAR}}"
          echo "Workflow env var: ${{env.WORKFLOW_VAR}}"
      - name: Overwritten variable env
        env:
          OVERWRITTEN: 'I have been overwritten at the step level'
        run: |
          echo "Step env var: ${{env.OVERWRITTEN}}"